### ISSUE TITLE
[Bug] Cinnabar is getting all of the oredict entries from the config file.

### ISSUE THREAD

**Issue by TeetoKaziim** [AmazigJj/SimplyGems#1]
None of the other gems are getting their oredictionary entries, and cinnabar is getting all of them.

https://i.imgur.com/uUGxVCu.png

Sorry. ; _ ;

**Comment by Wolferain** [comment]
Hi TeetoKaziim,
Thank you for contacting us. We will look further into the issue.

Wolferain

**Comment by AmazigJj** [comment]
haha such a formal reply :P

**Comment by AmazigJj** [comment]
fixed, update shall be posted on curseforge soon
