### ISSUE TITLE
simplygems-1.1.2.jar/assets/simplygems/blockstates/oreruby.json is missing.

### ISSUE THREAD

**Issue by TeetoKaziim** [AmazigJj/SimplyGems#3]
No json, no blockstate, no texture in-world ; _ ; 

https://i.imgur.com/Sjwslzl.png

**Comment by Wolferain** [comment]
Hi TeetoKaziim,
Thank you for contacting us. We will look further into the issue.

Wolferain

**Comment by AmazigJj** [comment]
fixed :D
